/* Auto-generated by scripts/gen-tokens.js from tokens/tokens.json. Do not edit directly. */

export const tokens = {
  "color": {
    "primary": {
      "hex": "#856AF9",
      "ansi256": 99,
      "desc": "rumo 品牌紫"
    },
    "success": {
      "hex": "#2ABC80",
      "ansi256": 36,
      "desc": "成功状态绿"
    },
    "warning": {
      "hex": "#FF9c29",
      "ansi256": 214,
      "desc": "告警状态橙"
    },
    "danger": {
      "hex": "#F45757",
      "ansi256": 203,
      "desc": "危险/错误红"
    },
    "info": {
      "hex": "#856AF9",
      "ansi256": 99,
      "desc": "信息提示紫"
    },
    "text": {
      "primary": {
        "hex": "#333333",
        "ansi256": 236,
        "desc": "主要正文"
      },
      "regular": {
        "hex": "#666666",
        "ansi256": 242,
        "desc": "常规文本"
      },
      "muted": {
        "hex": "#999999",
        "ansi256": 246,
        "desc": "弱化说明"
      }
    },
    "bg": {
      "terminal": {
        "hex": "#1e1e1e",
        "ansi256": 234,
        "desc": "控制台底色"
      }
    }
  },
  "spacing": {
    "xs": {
      "px": 4,
      "ch": 1
    },
    "sm": {
      "px": 8,
      "ch": 2
    },
    "md": {
      "px": 16,
      "ch": 4
    },
    "lg": {
      "px": 24,
      "ch": 6
    }
  },
  "border": {
    "style": {
      "web": "solid",
      "tui": "round"
    }
  }
} as const;

export type Tokens = typeof tokens;
export type TokenColor = keyof typeof tokens.color;
export type TokenSpacing = keyof typeof tokens.spacing;
