'use strict';

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const tokensFile = path.resolve(rootDir, 'tokens/tokens.json');
const scssOutFile = path.resolve(rootDir, 'packages/theme-chalk/src/common/tokens.scss');
const tsOutDir = path.resolve(rootDir, 'tui/src/tokens');
const tsOutFile = path.resolve(tsOutDir, 'index.ts');
const dashScssOutFile = path.resolve(rootDir, 'packages/theme-chalk/src/common/tokens-dash.scss');
const dashCssOutFile = path.resolve(rootDir, 'packages/theme-chalk/src/common/tokens-dash-css.scss');

if (!fs.existsSync(tokensFile)) {
  console.error(`Tokens source file not found: ${tokensFile}`);
  process.exit(1);
}

const raw = fs.readFileSync(tokensFile, 'utf8');
const tokens = JSON.parse(raw);

// 1. 生成 packages/theme-chalk/src/common/tokens.scss
let scssContent = `/* Auto-generated by scripts/gen-tokens.js from tokens/tokens.json. Do not edit directly. */\n\n`;

// Colors
scssContent += `/* Colors */\n`;
scssContent += `$--token-color-primary: ${tokens.color.primary.hex};\n`;
scssContent += `$--token-color-success: ${tokens.color.success.hex};\n`;
scssContent += `$--token-color-warning: ${tokens.color.warning.hex};\n`;
scssContent += `$--token-color-danger: ${tokens.color.danger.hex};\n`;
scssContent += `$--token-color-info: ${tokens.color.info.hex};\n\n`;

scssContent += `$--token-color-text-primary: ${tokens.color.text.primary.hex};\n`;
scssContent += `$--token-color-text-regular: ${tokens.color.text.regular.hex};\n`;
scssContent += `$--token-color-text-muted: ${tokens.color.text.muted.hex};\n\n`;

scssContent += `$--token-color-bg-terminal: ${tokens.color.bg.terminal.hex};\n\n`;

// Spacing
scssContent += `/* Spacing */\n`;
scssContent += `$--token-spacing-xs: ${tokens.spacing.xs.px}px;\n`;
scssContent += `$--token-spacing-sm: ${tokens.spacing.sm.px}px;\n`;
scssContent += `$--token-spacing-md: ${tokens.spacing.md.px}px;\n`;
scssContent += `$--token-spacing-lg: ${tokens.spacing.lg.px}px;\n\n`;

// Border
scssContent += `/* Border */\n`;
scssContent += `$--token-border-style: ${tokens.border.style.web};\n`;

fs.writeFileSync(scssOutFile, scssContent, 'utf8');
console.log(`[gen-tokens] SCSS tokens written to: ${scssOutFile}`);

// 2. 生成 tui/src/tokens/index.ts (为终端线预留类型安全入口)
if (!fs.existsSync(tsOutDir)) {
  fs.mkdirSync(tsOutDir, { recursive: true });
}

const tsContent = `/* Auto-generated by scripts/gen-tokens.js from tokens/tokens.json. Do not edit directly. */

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Tokens = typeof tokens;
export type TokenColor = keyof typeof tokens.color;
export type TokenSpacing = keyof typeof tokens.spacing;
`;

fs.writeFileSync(tsOutFile, tsContent, 'utf8');
console.log(`[gen-tokens] TS tokens written to: ${tsOutFile}`);

// ---------------------------------------------------------------------------
// 3/4. 生成 dash 皮肤层(tokens.dash 命名空间):
//   tokens-dash.scss     — SCSS 变量($--dash-*),组件样式编译期引用
//   tokens-dash-css.scss — 运行时 CSS 自定义变量(--rumo-*),挂 .rumo-dash 作用域
// hex 先声明(旧引擎兜底);oklch 值仅在 @supports 门控块内恢复
// (自定义属性不做 parse-time 校验,同块 hex→oklch fallback 无效)。
// ---------------------------------------------------------------------------
const dash = tokens.dash;

if (!dash || !dash.color || !dash.typography || !dash.radius || !dash.shadow || !dash.space) {
  console.error('tokens.dash namespace is missing or incomplete');
  process.exit(1);
}

const HEADER = `/* Auto-generated by scripts/gen-tokens.js from tokens/tokens.json. Do not edit directly. */\n`;

function colorEntries(colorMap, prefix) {
  // colorMap: { DEFAULT?, dark?, light?, 50..950?, ... } 值为 hex 字符串或 {hex, oklch?}
  const lines = [];
  Object.keys(colorMap).forEach((key) => {
    const val = colorMap[key];
    const hex = typeof val === 'string' ? val : val.hex;
    const name = key === 'DEFAULT' ? prefix : `${prefix}-${key}`;
    lines.push({ name, hex, oklch: (val && val.oklch) || null });
  });
  return lines;
}

function flatColorLines() {
  const c = dash.color;
  const lines = [];
  function push(prefix, val) {
    const hex = typeof val === 'string' ? val : val.hex;
    lines.push({ name: prefix, hex, oklch: (val && val.oklch) || null });
  }
  push('ink', c.ink);
  push('paper', c.paper);
  colorEntries(c.neutral, 'neutral').forEach((l) => lines.push(l));
  colorEntries(c.accent, 'accent').forEach((l) => lines.push(l));
  colorEntries(c.amber, 'amber').forEach((l) => lines.push(l));
  Object.keys(c.semantic).forEach((k) => push(k, c.semantic[k]));
  (c.series || []).forEach((v, i) => push(`series-${i + 1}`, v));
  return lines;
}

function darkColorLines() {
  const c = dash.color;
  const d = dash.colorDark || {};
  const lines = [];
  function push(prefix, val, oklchFrom) {
    if (!val) return;
    const hex = typeof val === 'string' ? val : val.hex;
    lines.push({ name: prefix, hex, oklch: (val && val.oklch) || oklchFrom || null });
  }
  // 暗色 ink/paper 与亮色互换(oklch 同步互换)
  push('ink', d.ink, c.paper && c.paper.oklch);
  push('paper', d.paper, c.ink && c.ink.oklch);
  if (d.neutral) colorEntries(d.neutral, 'neutral').forEach((l) => lines.push(l));
  if (d.accent) colorEntries(d.accent, 'accent').forEach((l) => lines.push(l));
  if (d.semantic) Object.keys(d.semantic).forEach((k) => push(k, d.semantic[k]));
  return lines;
}

// 3. tokens-dash.scss — SCSS 编译期变量
let dashScss = `${HEADER}\n`;
dashScss += `/* Dash skin colors — light */\n`;
flatColorLines().forEach((l) => {
  dashScss += `$--dash-color-${l.name}: ${l.hex};\n`;
});
dashScss += `\n/* Dash skin colors — dark overrides */\n`;
darkColorLines().forEach((l) => {
  dashScss += `$--dash-color-dark-${l.name}: ${l.hex};\n`;
});

dashScss += `\n/* Typography */\n`;
dashScss += `$--dash-font-sans: ${dash.typography.fontFamily.sans};\n`;
dashScss += `$--dash-font-mono: ${dash.typography.fontFamily.mono};\n`;
Object.keys(dash.typography.scale).forEach((step) => {
  const s = dash.typography.scale[step];
  dashScss += `$--dash-text-${step}-size: ${s.size};\n`;
  dashScss += `$--dash-text-${step}-lh: ${s.lineHeight};\n`;
  dashScss += `$--dash-text-${step}-weight: ${s.weight};\n`;
  if (s.letterSpacing) dashScss += `$--dash-text-${step}-ls: ${s.letterSpacing};\n`;
});

dashScss += `\n/* Radius */\n`;
Object.keys(dash.radius).forEach((k) => {
  dashScss += `$--dash-radius-${k}: ${dash.radius[k]};\n`;
});
dashScss += `\n/* Shadow */\n`;
Object.keys(dash.shadow).forEach((k) => {
  dashScss += `$--dash-shadow-${k}: ${dash.shadow[k]};\n`;
});
dashScss += `\n/* Space */\n`;
Object.keys(dash.space).forEach((k) => {
  dashScss += `$--dash-space-${k}: ${dash.space[k]};\n`;
});
dashScss += `\n/* Motion */\n`;
Object.keys(dash.motion).forEach((k) => {
  dashScss += `$--dash-motion-${k}: ${dash.motion[k]};\n`;
});
dashScss += `\n/* Breakpoint (min-height) */\n`;
Object.keys(dash.breakpoint).forEach((k) => {
  dashScss += `$--dash-bp-${k}: ${dash.breakpoint[k]};\n`;
});

fs.writeFileSync(dashScssOutFile, dashScss, 'utf8');
console.log(`[gen-tokens] Dash SCSS tokens written to: ${dashScssOutFile}`);

// 4. tokens-dash-css.scss — 运行时 CSS 自定义变量
let dashCss = `${HEADER}\n`;
dashCss += `.rumo-dash {\n`;
flatColorLines().forEach((l) => {
  dashCss += `  --rumo-c-${l.name}: ${l.hex};\n`;
});
dashCss += `\n  --rumo-font-sans: ${dash.typography.fontFamily.sans};\n`;
dashCss += `  --rumo-font-mono: ${dash.typography.fontFamily.mono};\n\n`;
Object.keys(dash.typography.scale).forEach((step) => {
  const s = dash.typography.scale[step];
  dashCss += `  --rumo-text-${step}-size: ${s.size};\n`;
  dashCss += `  --rumo-text-${step}-lh: ${s.lineHeight};\n`;
  dashCss += `  --rumo-text-${step}-weight: ${s.weight};\n`;
  if (s.letterSpacing) dashCss += `  --rumo-text-${step}-ls: ${s.letterSpacing};\n`;
});
dashCss += `\n`;
Object.keys(dash.radius).forEach((k) => {
  dashCss += `  --rumo-radius-${k}: ${dash.radius[k]};\n`;
});
dashCss += `\n`;
Object.keys(dash.shadow).forEach((k) => {
  dashCss += `  --rumo-shadow-${k}: ${dash.shadow[k]};\n`;
});
dashCss += `\n`;
Object.keys(dash.space).forEach((k) => {
  dashCss += `  --rumo-space-${k}: ${dash.space[k]};\n`;
});
dashCss += `\n`;
Object.keys(dash.motion).forEach((k) => {
  dashCss += `  --rumo-motion-${k}: ${dash.motion[k]};\n`;
});
dashCss += `\n`;
Object.keys(dash.breakpoint).forEach((k) => {
  dashCss += `  --rumo-bp-${k}: ${dash.breakpoint[k]};\n`;
});
dashCss += `}\n\n`;

dashCss += `.rumo-dash.is-dark {\n`;
darkColorLines().forEach((l) => {
  dashCss += `  --rumo-c-${l.name}: ${l.hex};\n`;
});
dashCss += `}\n\n`;

const oklchLight = flatColorLines().filter((l) => l.oklch);
const oklchDark = darkColorLines().filter((l) => l.oklch);
if (oklchLight.length || oklchDark.length) {
  dashCss += `/* Progressive enhancement: restore OKLCH on engines that support it.\n`;
  dashCss += `   Base declarations use sRGB hex so older Chromium/WebView2 (<111, no oklch()\n`;
  dashCss += `   parsing -> transparent custom properties) render correctly. Custom properties\n`;
  dashCss += `   are not parse-time validated, so a same-block hex->oklch fallback would NOT\n`;
  dashCss += `   work; the @supports gate is required. */\n`;
  dashCss += `@supports (color: oklch(0% 0 0)) {\n`;
  if (oklchLight.length) {
    dashCss += `  .rumo-dash {\n`;
    oklchLight.forEach((l) => {
      dashCss += `    --rumo-c-${l.name}: ${l.oklch};\n`;
    });
    dashCss += `  }\n`;
  }
  if (oklchDark.length) {
    dashCss += `  .rumo-dash.is-dark {\n`;
    oklchDark.forEach((l) => {
      dashCss += `    --rumo-c-${l.name}: ${l.oklch};\n`;
    });
    dashCss += `  }\n`;
  }
  dashCss += `}\n`;
}

fs.writeFileSync(dashCssOutFile, dashCss, 'utf8');
console.log(`[gen-tokens] Dash CSS tokens written to: ${dashCssOutFile}`);
