'use strict';

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const tokensFile = path.resolve(rootDir, 'tokens/tokens.json');
const scssOutFile = path.resolve(rootDir, 'packages/theme-chalk/src/common/tokens.scss');
const tsOutDir = path.resolve(rootDir, 'tui/src/tokens');
const tsOutFile = path.resolve(tsOutDir, 'index.ts');

if (!fs.existsSync(tokensFile)) {
  console.error(`Tokens source file not found: ${tokensFile}`);
  process.exit(1);
}

const raw = fs.readFileSync(tokensFile, 'utf8');
const tokens = JSON.parse(raw);

// 1. 生成 packages/theme-chalk/src/common/tokens.scss
let scssContent = `/* Auto-generated by scripts/gen-tokens.js from tokens/tokens.json. Do not edit directly. */\n\n`;

// Colors
scssContent += `/* Colors */\n`;
scssContent += `$--token-color-primary: ${tokens.color.primary.hex};\n`;
scssContent += `$--token-color-success: ${tokens.color.success.hex};\n`;
scssContent += `$--token-color-warning: ${tokens.color.warning.hex};\n`;
scssContent += `$--token-color-danger: ${tokens.color.danger.hex};\n`;
scssContent += `$--token-color-info: ${tokens.color.info.hex};\n\n`;

scssContent += `$--token-color-text-primary: ${tokens.color.text.primary.hex};\n`;
scssContent += `$--token-color-text-regular: ${tokens.color.text.regular.hex};\n`;
scssContent += `$--token-color-text-muted: ${tokens.color.text.muted.hex};\n\n`;

scssContent += `$--token-color-bg-terminal: ${tokens.color.bg.terminal.hex};\n\n`;

// Spacing
scssContent += `/* Spacing */\n`;
scssContent += `$--token-spacing-xs: ${tokens.spacing.xs.px}px;\n`;
scssContent += `$--token-spacing-sm: ${tokens.spacing.sm.px}px;\n`;
scssContent += `$--token-spacing-md: ${tokens.spacing.md.px}px;\n`;
scssContent += `$--token-spacing-lg: ${tokens.spacing.lg.px}px;\n\n`;

// Border
scssContent += `/* Border */\n`;
scssContent += `$--token-border-style: ${tokens.border.style.web};\n`;

fs.writeFileSync(scssOutFile, scssContent, 'utf8');
console.log(`[gen-tokens] SCSS tokens written to: ${scssOutFile}`);

// 2. 生成 tui/src/tokens/index.ts (为终端线预留类型安全入口)
if (!fs.existsSync(tsOutDir)) {
  fs.mkdirSync(tsOutDir, { recursive: true });
}

const tsContent = `/* Auto-generated by scripts/gen-tokens.js from tokens/tokens.json. Do not edit directly. */

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Tokens = typeof tokens;
export type TokenColor = keyof typeof tokens.color;
export type TokenSpacing = keyof typeof tokens.spacing;
`;

fs.writeFileSync(tsOutFile, tsContent, 'utf8');
console.log(`[gen-tokens] TS tokens written to: ${tsOutFile}`);
