// Icon data derived from Tabler Icons (MIT) — https://github.com/tabler/tabler-icons @0239805680a36bab4e1070529b6744924402d804
// Generated by D:\\backup\\gen-tabler-icons.js — do not hand-edit
import status from './status';
import actions from './actions';
import arrows from './arrows';
import files from './files';
import media from './media';
import editing from './editing';
import navigation from './navigation';
import communication from './communication';

export { status, actions, arrows, files, media, editing, navigation, communication };

export const icons = Object.assign({}, status, actions, arrows, files, media, editing, navigation, communication);

export default icons;
